Add item requests
anatolykalugin/java-shareit pull request #3
Opened 2022-10-26 16:21 UTC by anatolykalugin

2022-10-28 17:04 UTC, NikolaiDem requested changes

2022-10-28 17:04 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +    private ItemRequestService itemRequestService;
Внедрение лучше выполнять через конструктор. Поэтому можно сделать поле финальным и добавить @RequiredArgsConstructor для класса.

2022-10-28 17:04 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +    public static class Item {
Для большей наглядности лучше назвать ItemDto.

2022-10-28 17:04 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
> +@EqualsAndHashCode
Переопределять equals и hashcode нет необходимости.
Аналогично для всех остальных классов моделей.

2022-10-28 17:04 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +                    .map(itemRequest -> {
Здесь существует проблема N+1 запроса: Все (N) запросов ItemRequest были получены одним запросом. И теперь для каждого ItemRequest нужно сделать запрос и вытащить связанные с ним Item-s (дополнительно N запросов). Лучше одним запросом вытащить все Item-s (надо, конечно, учитывать, что они все поместятся в память). И уже на уровне Java распределить их по ItemRequest.
Аналогично для getOthersRequests(...)

2022-10-28 17:04 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +        if (userService.getUserById(requestorId) != null) {
Конструкции с меньшей вложенностью более удобны для чтения:
        if (userService.getUserById(requestorId) != null) {
            throw new NotFoundException("Данный пользователь не найден");
        }
        if (itemRequestDto.getDescription() != null && !itemRequestDto.getDescription().isBlank()) {
            User requestor = UserMapper.mapFrom(userService.getUserById(requestorId));
            ItemRequest itemRequest = ItemRequestDtoMapper.mapFrom(itemRequestDto, requestor);
            itemRequest.setCreated(LocalDateTime.now());
            itemRequestRepository.save(itemRequest);
            return ItemRequestDtoMapper.mapTo(itemRequest, null);
        } else {
            throw new ValidationException("Описание запроса не может быть пустым");
        }

Аналогично для остальных методов.

2022-10-28 17:04 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @OneToOne
Много вещей может быть у запроса. Значит, связь здесь ManyToOne.

2022-10-28 17:04 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +public class ItemRequestServiceImpl implements ItemRequestService {
Добавить логирование во все методы.

2022-10-28 17:04 UTC, NikolaiDem commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +package ru.practicum.shareit.booking;
Нужны еще тесты на BookingRepository (проверка кастомных запросов) и BookingMapper, ItemMapper, ItemRequestDtoMapper и UserMapper.

2022-10-28 19:37 UTC, anatolykalugin commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +    private ItemRequestService itemRequestService;
Исправлено

2022-10-28 19:37 UTC, anatolykalugin commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +    public static class Item {
Исправлено

2022-10-28 19:37 UTC, anatolykalugin commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
> +@EqualsAndHashCode
Исправлено

2022-10-28 19:38 UTC, anatolykalugin commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @OneToOne
Исправлено

2022-10-28 19:43 UTC, anatolykalugin commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +public class ItemRequestServiceImpl implements ItemRequestService {
Готово

2022-10-28 19:47 UTC, anatolykalugin commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +        if (userService.getUserById(requestorId) != null) {
Исправлено

2022-10-28 20:15 UTC, anatolykalugin commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +        if (userService.getUserById(requestorId) != null) {
При подобном выносе проверок фейлятся тесты постмана и, соответственно, в Гите. К тому же, становится больше строчек кода. Предлагаю оставить проверки как есть.

2022-10-28 20:18 UTC, anatolykalugin commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +package ru.practicum.shareit.booking;
Все кастомные запросы букингового репозитория проверяются в букингСервисИмплТесте. Все мапперы проверяются в тестах соответствующих классов: при неправильном маппинге тесты бы фейлились.

2022-10-28 20:21 UTC, anatolykalugin commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +                    .map(itemRequest -> {
Мне кажется, что оптимальнее все же оставить такую конструкцию, так как, во-первых, отдельная выкачка всех предметов (а их может быть сотни тысяч в рабочем сценарии) будет занимать гораздо больше памяти , во-вторых, будут дополнительные итерации по поиску среди них нужных для каждого реквеста -> займет больше времени. Предлагаю оставить как есть.

2022-10-28 20:48 UTC, anatolykalugin commented
Николай, внес изменения по большей части комментариев. По оставшимся предлагаю оставить как есть, причины указал в ответах к комментариям + постмановские/гитовские тесты оставляют мало пространства для творческой свободы :)

2022-10-29 19:52 UTC, NikolaiDem requested changes

2022-10-29 19:52 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +        if (userService.getUserById(requestorId) != null) {
В первом if конечно же проверка на равенство null. А так такой рефакторинг логику не меняет)

2022-10-29 19:52 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +                    .map(itemRequest -> {
Одномоментно памяти действительно потребуется больше. Но затраты по времени при большом количестве ItemRequest-ов с большой вероятностью будут меньше из-за одного обращения к БД вместо N. Потому просьба избавиться от множественных запросов)

2022-10-30 09:06 UTC, anatolykalugin commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +                    .map(itemRequest -> {
Теперь понял, исправил :)

2022-10-30 09:23 UTC, anatolykalugin commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +        if (userService.getUserById(requestorId) != null) {
Исправлено

2022-10-30 09:25 UTC, anatolykalugin commented
Все замечания исправлены

2022-10-31 07:51 UTC, NikolaiDem approved these changes

2022-10-31 07:51 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +            for (Item item : itemList) {
Сложность заполнения сейчас квадратичная. Лучше при чтении всех предметов преобразовать их в мапу, чтобы избавиться от полного перебора предметов в каждой итерации.

2022-11-01 16:43 UTC, merged